name: Example Workflow

on: [push]

permissions:
  contents: write
  checks: write
  packages: write

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Build with Maven
      run: mvn -B package

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()    # run this step even if previous step failed
      with:
        name: JUnit Tests            # Name of the check run which will be created
        path: target/surefire-reports/*.xml    # Path to test results
        reporter: java-junit
    - name: Upload to repository
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: target